services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Genre\Domain\Service\UploadService:
    arguments:
      - '%kernel.project_dir%/python/upload/'

  Genre\Domain\Service\ParserService: ~
  Genre\Domain\Service\ExperimentService: ~
