services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Genre\Web\Controller\ShowMainPageAction: ~
  Genre\Web\Controller\MusicMetrics\ShowMusicMetricsAction: ~
  Genre\Web\Controller\MusicMetrics\UploadAction: ~
