doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        server_version: '5.7.20'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            MusicMetrics:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/MusicMetrics/Entity'
                prefix: 'Genre\Domain\MusicMetrics\Entity'
            AudioFile:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/AudioFile/Entity'
                prefix: 'Genre\Domain\AudioFile\Entity'
