show_main_page:
  path: /
  controller: 'Genre\Web\Controller\ShowMainPageAction'
  methods: [GET]

music_metrics:
  path: /musicMetrics
  controller: 'Genre\Web\Controller\MusicMetrics\ShowMusicMetricsAction'
  methods: [GET]

upload:
  path: /upload
  controller: 'Genre\Web\Controller\MusicMetrics\UploadAction'
  methods: [POST]

experiment:
  path: /experiment
  controller: 'Genre\Web\Controller\Experiment\ShowExperimentAction'
  methods: [GET]

experiment_result:
  path: /experiment/result
  controller: 'Genre\Web\Controller\Experiment\ShowExperimentResultAction'
  methods: [POST]
